-- Public Access Configuration for Projects
-- Enables projects to have a public-facing survey/chat interface at /r/:slug
-- Replaces the separate research_links table with integrated project config

-- Add public access columns to projects table
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS public_slug text;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS public_hero_title text;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS public_hero_subtitle text;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS public_cta_label text DEFAULT 'Share your feedback';
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS public_cta_helper text;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS public_allow_chat boolean DEFAULT false;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS public_redirect_url text;
ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS public_calendar_url text;

-- Unique index for public slug lookup (only on non-null slugs)
CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_public_slug
  ON public.projects(public_slug)
  WHERE public_slug IS NOT NULL;

-- Index for finding public projects by account
CREATE INDEX IF NOT EXISTS idx_projects_account_public
  ON public.projects(account_id, is_public)
  WHERE is_public = true;

-- Comments for documentation
COMMENT ON COLUMN public.projects.public_slug IS 'URL slug for public access at /r/:slug. Generated by app using nanoid BASE58 (6 chars).';
COMMENT ON COLUMN public.projects.is_public IS 'Whether the project is accessible via public link';
COMMENT ON COLUMN public.projects.public_hero_title IS 'Title displayed on public survey page';
COMMENT ON COLUMN public.projects.public_hero_subtitle IS 'Subtitle/description on public survey page';
COMMENT ON COLUMN public.projects.public_cta_label IS 'Call-to-action button text (default: Share your feedback)';
COMMENT ON COLUMN public.projects.public_cta_helper IS 'Helper text below the CTA button';
COMMENT ON COLUMN public.projects.public_allow_chat IS 'Whether AI chat mode is enabled for public responses';
COMMENT ON COLUMN public.projects.public_redirect_url IS 'URL to redirect to after survey completion';
COMMENT ON COLUMN public.projects.public_calendar_url IS 'Optional calendar booking link to show on public page';

-- Note: public_slug is generated by the application using nanoid BASE58 (6 chars)
-- No auto-generation trigger needed - slugs come from app/utils/slug.ts
-- Example: 'f3GkQp', 'aBc123'

-- Drop old auto-generation triggers if they exist
DROP TRIGGER IF EXISTS projects_auto_generate_public_slug ON public.projects;
DROP TRIGGER IF EXISTS projects_slugify_public_slug ON public.projects;
DROP FUNCTION IF EXISTS public.auto_generate_public_slug();
DROP FUNCTION IF EXISTS public.slugify_public_slug();
