name = "upsight-file-gateway"
main = "src/index.ts"
compatibility_date = "2025-09-19"

r2_buckets = [{ binding = "R2", bucket_name = "upsight-usermedia" }]

[vars]
# none; use secrets for sensitive values
